name: MapHider
version: '${version}'

main: org.hax.maphider.MapHider
api-version: '1.21'
depend:
  - Pl3xMap
load: STARTUP

commands:
  maphider:
    description: Reload configuration
    usage: /maphider reload

permission:
  maphider.reload:
    description: Allows to reload maphider config
    default: op

authors: [ Hax ]
